### ISSUE TITLE
use pyramid.session.PickleSerializer

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_nacl_session#2] opened 2015-11-18 19:58 UTC
This isn't much, but it might be useful to make your `EncryptingPickleSerializer` split out into just an `EncryptingSerializer` that uses the bytes from pyramid's default `PickleSerializer`. Composibility means your encryption code could be used with a json serializer for some people who care.

**Comment by tseaver** [comment] 2015-11-18 20:00
Maybe -- its hard to see how anyone could care, given that the serialized form is completely opaque by design.

**Comment by tseaver** [comment] 2015-11-18 20:01
I guess somebody might be able to use `libsodium` from within a `node.js` app (or whatever) to consume the same session.

**Comment by mmerickel** [comment] 2015-11-18 20:04
Yeah, I know for a fact some people are using json for sessions despite it violating the `ISession` api. Regardless the encryption code should stand on its own without being coupled to anything. Of course you might want to still expose an `EncryptingPickleSerializer` object, or something similar by default.

**Comment by mmerickel** [comment] 2015-11-18 20:04
This design is the same as how pyramid's default sessions do `SignedSerializer` composing with `PickleSerializer`.

**Comment by mmerickel** [comment] 2015-11-18 20:06
Side note we use `SignedSerializer` so maybe `EncryptedSerializer` is better than encrypting but hey.. just something to point out incase you want to go for that level of conformance.

**Comment by tseaver** [comment] 2015-11-18 20:07
My point is that pickle vs. json is moot for this case unless you can independently decrypt the cookie somehow, which is out of scope for my usecase.  I'm going to leave this open, but ignore it (my client doesn't need it, and I'm out of budget).  I'd be willing to review / merge a PR which made that possible.

**Comment by tseaver** [comment] 2015-11-18 20:08
Thanks for the review, BTW!

**Comment by mmerickel** [comment] 2015-11-18 20:09
Fair enough, I will probably submit a PR for it. :-) I'm looking forward to using this library. Fortunately nacl has bindings to tons of languages so decryption shouldn't be difficult assuming a non-pickle format.

**Comment by mikeorr** [comment] 2015-11-19 03:56
On Wed, Nov 18, 2015 at 12:04 PM, Michael Merickel <notifications@github.com

> wrote:
> 
> Yeah, I know for a fact some people are using json for sessions despite it
> violating the ISession api.

It's a shortcoming in the API. JSON is text-readable, pickle protocol 1 is
more cumbersome, and the current pickle proocol optimized for new-style
classes is binary.

I'm using JSON with 'pyramid_redis_sessions'. Although it's still not
optimal with redis-cli, because it displays the value with backslashed
quotes. Also, earlier I said I wanted to try storing the session dict in a
native Redis hash. That turned out to be even more cumbersome because you
can't 'get' a hash; you have to know the type of the value and use a
type-specific list command. 'set' is universal: it will overwrite any type
with a string, but 'get' is string-specific.

**Comment by mikeorr** [comment] 2015-11-19 03:57
Sorry for posting to the ticket; I thought it was going to pylons-discuss.

On Wed, Nov 18, 2015 at 7:56 PM, Mike Orr sluggoster@gmail.com wrote:

> On Wed, Nov 18, 2015 at 12:04 PM, Michael Merickel
> notifications@github.com wrote:
> 
> > Yeah, I know for a fact some people are using json for sessions despite it
> > violating the ISession api.
> 
> It's a shortcoming in the API. JSON is text-readable, pickle protocol 1 is
> more cumbersome, and the current pickle proocol optimized for new-style
> classes is binary.
> 
> I'm using JSON with 'pyramid_redis_sessions'. Although it's still not
> optimal with redis-cli, because it displays the value with backslashed
> quotes. Also, earlier I said I wanted to try storing the session dict in a
> native Redis hash. That turned out to be even more cumbersome because you
> can't 'get' a hash; you have to know the type of the value and use a
> type-specific list command. 'set' is universal: it will overwrite any type
> with a string, but 'get' is string-specific.

## 

Mike Orr sluggoster@gmail.com

**Comment by digitalresistor** [comment] 2015-11-23 18:15
I personally use JSON for my sessions, yes in violation of the `ISession` API because if my key were to somehow be compromised, then an attacker could only generate fake session data, they couldn't for instance get full executable control over my process...

**Comment by tseaver** [comment] 2015-11-23 19:00
@mikeorr Somehow, I don't think human-readability is going to matter for encrypted cookies.

@bertjwregeer Isn't the pickle risk is kind of moot for an encrypted/signed session?  If they've got your key, either they're all up in your filesystem, in which case Game Over already;  or else they can't get you to unpickle something which gives them control, because they can't inject an Evil Class (TM).

**Comment by digitalresistor** [comment] 2015-11-23 19:30
@tseaver or someone pushed the encryption key to a public repo on accident, and the attacker doesn't have access to my system yet... with pickle they are now a step closer, without, they can create fake sessions.

**Comment by tseaver** [comment] 2015-11-23 19:40
Via PR #4.

**Closed as completed by tseaver** 2015-11-23 19:40 UTC
